### ISSUE TITLE
Code Broke With PayPal Here Version 3.0.2 

### ISSUE THREAD

**Issue by bfleishman** [paypal/here-sideloader-api-samples#54]
I integrated this code into my web app a couple years ago and it has been working great! However when I updated my PayPal Here app recently on my iPad to version 3.0.2, the integration stopped working.

I receive an error in my my PayPal app and it initial open from the URI encoded link that says the following:

**Invalid Link
The link that you opened was not correctly formatted. Please check with the creator of the link.**

I have confirmed that this is not an issue with my code and the data that I am encoding as your sample page generated the same error. https://github.com/paypal/here-sideloader-api-samples/blob/master/docs/sample.html

Can anyone help me decipher this error? I am desperately seeking assistance. It should be easily recreated with the sample code as previously posted. Thank you.

**Comment by Grismy** [comment]
Same problem.
It looks like something changes in the request format, but I can't find any documentation about it.

**Comment by Pivovar63** [comment]
Yes, the same. And no answer from Paypal technical support.

**Comment by bfleishman** [comment]
Gave up and switched to the Square web API instead. Works the same and has better [documentation](https://docs.connect.squareup.com/articles/web-api-ios ) and support. Got immediate help with implementation through their [stack-overflow forum](https://stackoverflow.com/questions/tagged/square-connect) as well. 

If you need assistance I can help with the little bit of knowledge I've gained implementing it on my end.

**Comment by paypalsathya** [comment]
Yes, in the latest version of the app, sideloader was broken. We have implemented the required fixes on the PayPal Here app to support this going forward. 
The app should be available on the app store end of this week or early next week.

Apologies for the delayed response 😞

**Comment by paypalsathya** [comment]
The latest PayPal Here app should now be available on the app store. Please download that and try out your sideloader application. Should be working now 😸

**Comment by Grismy** [comment]
It works! Thanks.

**Comment by glaidler** [comment]
This is still broken.  After updating app, I am getting consistent DECLINED.  **This happens with your sample HTML page as well as my own implementation**.  Please can you advise urgently?

I am using v3.0.6 and using web sideloader api.

**Comment by snehanshuashar** [comment]
The payments are being declined because if there is a phone number, then the country code is also a required field. To keep things simple and fix the issue, you could skip the payerPhone part from the pphereUrl: https://github.com/paypal/here-sideloader-api-samples/pull/57/files#diff-63649daa8f3846155161473034fdf217R21

**Comment by glaidler** [comment]
This worked for me. thanks
