### ISSUE TITLE
Is Sideloader API operational with the Paypal Here 3.2.4

### ISSUE THREAD

**Issue by dooms99** [paypal/here-sideloader-api-samples#63]
Our app first broke when updating to 3.081.  It would call the app but typically not populate the transaction value.   If it would populate the value it stopped returning to the application (and returing the payment status) when choosing New Sale.   Should this be functioning at this point.  I don't see any response to the breakage at 3.0.81 post so I am assuming it is misbehaving in some way in that version at later versions.  Should I abandon trying to use sideloader API at all?

**Comment by DJ92** [comment]
Hey @dooms99 , The behavior you're mentioning should be working in the latest app release. We had an issue where the transaction ID/auth code value wasn't getting returned in the return URL. This has been fixed and is currently being throttled out to all users in v3.2.3 (323001). Thanks

**Comment by ghost** [comment]
@DJ92 We're trying the latest version (3.2.3 for iOS) after also having our application broken since 3.081.  When we click "New Sale" after the process is complete, the user still isn't returned to our application, but instead has the PayPal Here app try to start a new transaction within PayPal Here.  Any suggestions?  Thanks for your time.

**Comment by DJ92** [comment]
Hey @EventRebels, I have tested this thoroughly and seems like the returnURL works as desired. Can you check your returnURL matches the format of the sample txn that I just did today? Eg:
http://mysterious-caverns-98085.herokuapp.com/handler.php?Type={Type}&InvoiceId={InvoiceId}&Tip={Tip}&Email={Email}&TxId={TxId}&Number={Number}&accepted=cash,card,paypal&step=choosePayment&invoice={"itemList":{"item":[{"name":"Hamburger","description":"1/4 lb burger with catsup, mustard, onion, pickle","quantity":"1","unitPrice":"3.50","taxRate":"5.0","taxName":"NE Tax"}]},"paymentTerms":"DueOnReceipt","currencyCode":"USD","number":"WEBSL180816094423","merchantEmail":"XXXXXXXXXXX@gmail.com","payerEmail":"XXXX@XXXXX.com"}

**Comment by ghost** [comment]
@DJ92 We were able to get everything working again, thanks for the new release

**Comment by DJ92** [comment]
@EventRebels That's good to hear!

**Comment by dooms99** [comment]
So in real world testing we have found that after doing a couple of transactions they begin to fail if done through the sideloader api but are successful if done directly.  This has happened across numerous events for us now.  Any suggestions to look at that would cause this type of behavior?
